(function(b){function g(d){if(c[d])return c[d].exports;var h=c[d]={exports:{},id:d,loaded:!1};b[d].call(h.exports,h,h.exports,g);h.loaded=!0;return h.exports}var c={};g.m=b;g.c=c;g.p="";return g(0)})({0:function(b,g,c){b=(b=c(141))&&b.__esModule?b:{default:b};b.default.precache("/ /soundcloud-16.png /soundcloud-32.png /soundcloud-64.png /soundcloud-128.png /soundcloud-256.png /soundcloud-512.png".split(" "));b.default.router.get("/",b.default.cacheFirst);b.default.router.get(/.*client.*/,b.default.cacheFirst);
b.default.router.get(/^.*googleapis.*$/,b.default.cacheFirst);b.default.router.get(/^.*gstatic.*$/,b.default.cacheFirst);b.default.router.get(/^.*bootstrapcdn.*$/,b.default.cacheFirst);b.default.router.get(/^.*sndcdn.*$/,b.default.cacheFirst);self.addEventListener("install",function(b){b.waitUntil(self.skipWaiting())});self.addEventListener("activate",function(b){b.waitUntil(self.clients.claim())})},141:function(b,g,c){c(142);var d=c(143),h=c(144),k=c(148);g=c(150);k.debug("Service Worker Toolbox is loading");
var a=function(a){return a.reduce(function(f,l){return f.concat(l)},[])},e=function(a){var f=Array.isArray(a);f&&a.forEach(function(a){"string"===typeof a||a instanceof Request||(f=!1)});if(!f)throw new TypeError("The precache method expects either an array of strings and/or Requests or a Promise that resolves to an array of strings and/or Requests.");return a};self.addEventListener("install",function(m){var f=d.cache.name+"$$$inactive$$$";k.debug("install event fired");k.debug("creating cache ["+
f+"]");m.waitUntil(k.openCache({cache:{name:f}}).then(function(f){return Promise.all(d.preCacheItems).then(a).then(e).then(function(a){k.debug("preCache list: "+(a.join(", ")||"(none)"));return f.addAll(a)})}))});self.addEventListener("activate",function(a){k.debug("activate event fired");a.waitUntil(k.renameCache(d.cache.name+"$$$inactive$$$",d.cache.name))});self.addEventListener("fetch",function(a){var f=h.match(a.request);f?a.respondWith(f(a.request)):h.default&&"GET"===a.request.method&&a.respondWith(h.default(a.request))});
b.exports={networkOnly:g.networkOnly,networkFirst:g.networkFirst,cacheOnly:g.cacheOnly,cacheFirst:g.cacheFirst,fastest:g.fastest,router:h,options:d,cache:function(a,f){return k.openCache(f).then(function(f){return f.add(a)})},uncache:function(a,f){return k.openCache(f).then(function(f){return f.delete(a)})},precache:function(a){a instanceof Promise||e(a);d.preCacheItems=d.preCacheItems.concat(a)}}},142:function(b,g){(function(){var b=Cache.prototype.addAll,d=navigator.userAgent.match(/(Firefox|Chrome)\/(\d+\.)/);
if(d)var h=d[1],k=parseInt(d[2]);b&&(!d||"Firefox"===h&&46<=k||"Chrome"===h&&50<=k)||(Cache.prototype.addAll=function(a){function e(a){this.name="NetworkError";this.code=19;this.message=a}var b=this;e.prototype=Object.create(Error.prototype);return Promise.resolve().then(function(){if(1>arguments.length)throw new TypeError;a=a.map(function(a){return a instanceof Request?a:String(a)});return Promise.all(a.map(function(a){"string"===typeof a&&(a=new Request(a));var l=(new URL(a.url)).protocol;if("http:"!==
l&&"https:"!==l)throw new e("Invalid scheme");return fetch(a.clone())}))}).then(function(f){if(f.some(function(a){return!a.ok}))throw new e("Incorrect response status");return Promise.all(f.map(function(f,e){return b.put(a[e],f)}))}).then(function(){})},Cache.prototype.add=function(a){return this.addAll([a])})})()},143:function(b,g){var c;c=self.registration?self.registration.scope:self.scope||(new URL("./",self.location)).href;b.exports={cache:{name:"$$$toolbox-cache$$$"+c+"$$$",maxAgeSeconds:null,
maxEntries:null},debug:!1,networkTimeoutSeconds:null,preCacheItems:[],successResponses:/^0|([123]\d\d)|(40[14567])|410$/}},144:function(b,g,c){var d=c(145),h=function(a,e){for(var b=a.entries(),f=b.next(),l=[];!f.done;)(new RegExp(f.value[0])).test(e)&&l.push(f.value[1]),f=b.next();return l},k=function(){this.routes=new Map;this.routes.set(RegExp,new Map);this.default=null};"get post put delete head any".split(" ").forEach(function(a){k.prototype[a]=function(e,b,f){return this.add(a,e,b,f)}});k.prototype.add=
function(a,e,b,f){f=f||{};var l;e instanceof RegExp?l=RegExp:(l=f.origin||self.location.origin,l=l instanceof RegExp?l.source:l.replace(/[-\/\\^$*+?.()|[\]{}]/g,"\\$&"));a=a.toLowerCase();e=new d(a,e,b,f);this.routes.has(l)||this.routes.set(l,new Map);l=this.routes.get(l);l.has(a)||l.set(a,new Map);l.get(a).set((e.regexp||e.fullUrlRegExp).source,e)};k.prototype.matchMethod=function(a,b){var d=new URL(b),f=d.pathname;return this._match(a,h(this.routes,d.origin),f)||this._match(a,[this.routes.get(RegExp)],
b)};k.prototype._match=function(a,b,d){if(0===b.length)return null;for(var f=0;f<b.length;f++){var l=b[f];if(l=l&&l.get(a.toLowerCase()))if(l=h(l,d),0<l.length)return l[0].makeHandler(d)}return null};k.prototype.match=function(a){return this.matchMethod(a.method,a.url)||this.matchMethod("any",a.url)};b.exports=new k},145:function(b,g,c){var d=(new URL("./",self.location)).pathname,h=c(146);g=function(b,a,e,c){a instanceof RegExp?this.fullUrlRegExp=a:(0!==a.indexOf("/")&&(a=d+a),this.keys=[],this.regexp=
h(a,this.keys));this.method=b;this.options=c;this.handler=e};g.prototype.makeHandler=function(b){var a;if(this.regexp){var e=this.regexp.exec(b);a={};this.keys.forEach(function(b,f){a[b.name]=e[f+1]})}return function(b){return this.handler(b,a,this.options)}.bind(this)};b.exports=g},146:function(b,g,c){function d(a){for(var f=[],b=0,l=0,e="",d;null!=(d=n.exec(a));){var c=d[0],h=d[1],k=d.index,e=e+a.slice(l,k),l=k+c.length;if(h)e+=h[1];else{var u=a[l],c=d[2],h=d[3],q=d[4],g=d[5],m=d[6],k=d[7];e&&(f.push(e),
e="");var u=null!=c&&null!=u&&u!==c,w="+"===m||"*"===m,m="?"===m||"*"===m;d=d[2]||"/";q=q||g||(k?".*":"[^"+d+"]+?");f.push({name:h||b++,prefix:c||"",delimiter:d,optional:m,repeat:w,partial:u,asterisk:!!k,pattern:q.replace(/([=!:$\/()])/g,"\\$1")})}}l<a.length&&(e+=a.substr(l));e&&f.push(e);return f}function h(a){return encodeURI(a).replace(/[\/?#]/g,function(a){return"%"+a.charCodeAt(0).toString(16).toUpperCase()})}function k(a){return encodeURI(a).replace(/[?#]/g,function(a){return"%"+a.charCodeAt(0).toString(16).toUpperCase()})}
function a(a){for(var f=Array(a.length),b=0;b<a.length;b++)"object"===typeof a[b]&&(f[b]=new RegExp("^(?:"+a[b].pattern+")$"));return function(b,l){for(var e="",d=b||{},c=(l||{}).pretty?h:encodeURIComponent,t=0;t<a.length;t++){var m=a[t];if("string"===typeof m)e+=m;else{var g=d[m.name],n;if(null==g)if(m.optional){m.partial&&(e+=m.prefix);continue}else throw new TypeError('Expected "'+m.name+'" to be defined');if(q(g)){if(!m.repeat)throw new TypeError('Expected "'+m.name+'" to not repeat, but received `'+
JSON.stringify(g)+"`");if(0===g.length)if(m.optional)continue;else throw new TypeError('Expected "'+m.name+'" to not be empty');for(var v=0;v<g.length;v++){n=c(g[v]);if(!f[t].test(n))throw new TypeError('Expected all "'+m.name+'" to match "'+m.pattern+'", but received `'+JSON.stringify(n)+"`");e+=(0===v?m.prefix:m.delimiter)+n}}else{n=m.asterisk?k(g):c(g);if(!f[t].test(n))throw new TypeError('Expected "'+m.name+'" to match "'+m.pattern+'", but received "'+n+'"');e+=m.prefix+n}}}return e}}function e(a){return a.replace(/([.+*?=^!:${}()[\]|\/\\])/g,
"\\$1")}function m(a,f){a.keys=f;return a}function f(a,f){f=f||{};for(var b=f.strict,l=!1!==f.end,d="",c=a[a.length-1],c="string"===typeof c&&/\/$/.test(c),m=0;m<a.length;m++){var h=a[m];if("string"===typeof h)d+=e(h);else{var k=e(h.prefix),g="(?:"+h.pattern+")";h.repeat&&(g+="(?:"+k+g+")*");g=h.optional?h.partial?k+"("+g+")?":"(?:"+k+"("+g+"))?":k+"("+g+")";d+=g}}b||(d=(c?d.slice(0,-2):d)+"(?:\\/(?=$))?");return new RegExp("^"+(l?d+"$":d+(b&&c?"":"(?=\\/|$)")),f.sensitive?"":"i")}function l(a,b,
e){b=b||[];q(b)?e||(e={}):(e=b,b=[]);if(a instanceof RegExp){if(e=a.source.match(/\((?!\?)/g))for(var c=0;c<e.length;c++)b.push({name:c,prefix:null,delimiter:null,optional:!1,repeat:!1,partial:!1,asterisk:!1,pattern:null});return m(a,b)}if(q(a)){for(var c=[],h=0;h<a.length;h++)c.push(l(a[h],b,e).source);a=new RegExp("(?:"+c.join("|")+")",e.sensitive?"":"i");return m(a,b)}a=d(a);e=f(a,e);for(c=0;c<a.length;c++)"string"!==typeof a[c]&&b.push(a[c]);return m(e,b)}var q=c(147);b.exports=l;b.exports.parse=
d;b.exports.compile=function(b){return a(d(b))};b.exports.tokensToFunction=a;b.exports.tokensToRegExp=f;var n=/(\\.)|([\/.])?(?:(?:\:(\w+)(?:\(((?:\\.|[^\\()])+)\))?|\(((?:\\.|[^\\()])+)\))([+*?])?|(\*))/g},147:function(b,g){b.exports=Array.isArray||function(b){return"[object Array]"==Object.prototype.toString.call(b)}},148:function(b,g,c){function d(b,e){e=e||{};(e.debug||a.debug)&&console.log("[sw-toolbox] "+b)}function h(b){var e;b&&b.cache&&(e=b.cache.name);e=e||a.cache.name;return caches.open(e)}
function k(a,b,c){var h=a.url,m=c.maxAgeSeconds,k=c.maxEntries;a=c.name;var g=Date.now();d("Updating LRU order for "+h+". Max entries is "+k+", max age is "+m);return e.getDb(a).then(function(a){return e.setTimestampForUrl(a,h,g)}).then(function(a){return e.expireEntries(a,k,m,g)}).then(function(a){d("Successfully updated IDB.");a=a.map(function(a){return b.delete(a)});return Promise.all(a).then(function(){d("Done with cache cleanup.")})}).catch(function(a){d(a)})}var a=c(143),e=c(149),m;b.exports=
{debug:d,fetchAndCache:function(b,e){e=e||{};var d=e.successResponses||a.successResponses;return fetch(b.clone()).then(function(c){"GET"===b.method&&d.test(c.status)&&h(e).then(function(d){d.put(b,c).then(function(){var c=e.cache||a.cache;(c.maxEntries||c.maxAgeSeconds)&&c.name&&(c=k.bind(null,b,d,c),m=m?m.then(c):c())})});return c.clone()})},openCache:h,renameCache:function(a,b,e){d("Renaming cache: ["+a+"] to ["+b+"]",e);return caches.delete(b).then(function(){return Promise.all([caches.open(a),
caches.open(b)]).then(function(b){var e=b[0],c=b[1];return e.keys().then(function(a){return Promise.all(a.map(function(a){return e.match(a).then(function(b){return c.put(a,b)})}))}).then(function(){return caches.delete(a)})})})}}},149:function(b,g){function c(a){return new Promise(function(b,c){var d=indexedDB.open("sw-toolbox-"+a,1);d.onupgradeneeded=function(){d.result.createObjectStore("store",{keyPath:"url"}).createIndex("timestamp","timestamp",{unique:!1})};d.onsuccess=function(){b(d.result)};
d.onerror=function(){c(d.error)}})}function d(a,b,d){return b?new Promise(function(c,h){var k=1E3*b,g=[],p=a.transaction("store","readwrite"),r=p.objectStore("store");r.index("timestamp").openCursor().onsuccess=function(a){if((a=a.target.result)&&d-k>a.value.timestamp){var b=a.value.url;g.push(b);r.delete(b);a.continue()}};p.oncomplete=function(){c(g)};p.onabort=h}):Promise.resolve([])}function h(a,b){return b?new Promise(function(d,c){var h=[],g=a.transaction("store","readwrite"),k=g.objectStore("store"),
p=k.index("timestamp"),r=p.count();p.count().onsuccess=function(){var a=r.result;a>b&&(p.openCursor().onsuccess=function(d){if(d=d.target.result){var c=d.value.url;h.push(c);k.delete(c);a-h.length>b&&d.continue()}})};g.oncomplete=function(){d(h)};g.onabort=c}):Promise.resolve([])}var k={};b.exports={getDb:function(a){a in k||(k[a]=c(a));return k[a]},setTimestampForUrl:function(a,b,d){return new Promise(function(c,h){var g=a.transaction("store","readwrite");g.objectStore("store").put({url:b,timestamp:d});
g.oncomplete=function(){c(a)};g.onabort=function(){h(g.error)}})},expireEntries:function(a,b,c,f){return d(a,c,f).then(function(d){return h(a,b).then(function(a){return d.concat(a)})})}}},150:function(b,g,c){b.exports={networkOnly:c(151),networkFirst:c(152),cacheOnly:c(153),cacheFirst:c(154),fastest:c(155)}},151:function(b,g,c){var d=c(148);b.exports=function(b,c,a){d.debug("Strategy: network only ["+b.url+"]",a);return fetch(b)}},152:function(b,g,c){var d=c(143),h=c(148);b.exports=function(b,a,c){c=
c||{};var g=c.successResponses||d.successResponses,f=c.networkTimeoutSeconds||d.networkTimeoutSeconds;h.debug("Strategy: network first ["+b.url+"]",c);return h.openCache(c).then(function(a){var d,n=[],p;if(f){var r=new Promise(function(c){d=setTimeout(function(){a.match(b).then(function(a){a&&c(a)})},1E3*f)});n.push(r)}r=h.fetchAndCache(b,c).then(function(a){d&&clearTimeout(d);if(g.test(a.status))return a;h.debug("Response was an HTTP error: "+a.statusText,c);p=a;throw Error("Bad response");}).catch(function(d){h.debug("Network or response error, fallback to cache ["+
b.url+"]",c);return a.match(b).then(function(a){if(a)return a;if(p)return p;throw d;})});n.push(r);return Promise.race(n)})}},153:function(b,g,c){var d=c(148);b.exports=function(b,c,a){d.debug("Strategy: cache only ["+b.url+"]",a);return d.openCache(a).then(function(a){return a.match(b)})}},154:function(b,g,c){var d=c(148);b.exports=function(b,c,a){d.debug("Strategy: cache first ["+b.url+"]",a);return d.openCache(a).then(function(c){return c.match(b).then(function(c){return c?c:d.fetchAndCache(b,
a)})})}},155:function(b,g,c){var d=c(148),h=c(153);b.exports=function(b,a,c){d.debug("Strategy: fastest ["+b.url+"]",c);return new Promise(function(g,f){var l=!1,q=[],n=function(a){q.push(a.toString());l?f(Error('Both cache and network failed: "'+q.join('", "')+'"')):l=!0},p=function(a){a instanceof Response?g(a):n("No result returned")};d.fetchAndCache(b.clone(),c).then(p,n);h(b,a,c).then(p,n)})}}});
