var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,f,e){if(e.get||e.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[f]=e.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,f,e,d){if(f){e=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var h=a[d];h in e||(e[h]={});e=e[h]}a=a[a.length-1];d=e[a];f=f(d);f!=d&&null!=f&&$jscomp.defineProperty(e,a,{configurable:!0,writable:!0,value:f})}};$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;
$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};
$jscomp.arrayIterator=function(a){var f=0;return $jscomp.iteratorPrototype(function(){return f<a.length?{done:!1,value:a[f++]}:{done:!0}})};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.array=$jscomp.array||{};
$jscomp.iteratorFromArray=function(a,f){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var e=0,d={next:function(){if(e<a.length){var h=e++;return{value:f(h,a[h]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};$jscomp.polyfill("Array.prototype.entries",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a,e){return[a,e]})}},"es6-impl","es3");
$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();var f=a[Symbol.iterator];return f?f.call(a):$jscomp.arrayIterator(a)};$jscomp.owns=function(a,f){return Object.prototype.hasOwnProperty.call(a,f)};
$jscomp.polyfill("WeakMap",function(a){function f(b){$jscomp.owns(b,d)||$jscomp.defineProperty(b,d,{value:{}})}function e(b){var c=Object[b];c&&(Object[b]=function(b){f(b);return c(b)})}if(function(){if(!a||!Object.seal)return!1;try{var b=Object.seal({}),c=Object.seal({}),d=new a([[b,2],[c,3]]);if(2!=d.get(b)||3!=d.get(c))return!1;d.delete(b);d.set(c,4);return!d.has(b)&&4==d.get(c)}catch(l){return!1}}())return a;var d="$jscomp_hidden_"+Math.random().toString().substring(2);e("freeze");e("preventExtensions");
e("seal");var h=0,g=function(b){this.id_=(h+=Math.random()+1).toString();if(b){$jscomp.initSymbol();$jscomp.initSymbolIterator();b=$jscomp.makeIterator(b);for(var c;!(c=b.next()).done;)c=c.value,this.set(c[0],c[1])}};g.prototype.set=function(b,c){f(b);if(!$jscomp.owns(b,d))throw Error("WeakMap key fail: "+b);b[d][this.id_]=c;return this};g.prototype.get=function(b){return $jscomp.owns(b,d)?b[d][this.id_]:void 0};g.prototype.has=function(b){return $jscomp.owns(b,d)&&$jscomp.owns(b[d],this.id_)};g.prototype.delete=
function(b){return $jscomp.owns(b,d)&&$jscomp.owns(b[d],this.id_)?delete b[d][this.id_]:!1};return g},"es6-impl","es3");$jscomp.ASSUME_NO_NATIVE_MAP=!1;
$jscomp.polyfill("Map",function(a){if(!$jscomp.ASSUME_NO_NATIVE_MAP&&function(){if(!a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),b=new a($jscomp.makeIterator([[c,"s"]]));if("s"!=b.get(c)||1!=b.size||b.get({x:4})||b.set({x:4},"t")!=b||2!=b.size)return!1;var d=b.entries(),g=d.next();if(g.done||g.value[0]!=c||"s"!=g.value[1])return!1;g=d.next();return g.done||4!=g.value[0].x||"t"!=g.value[1]||!d.next().done?!1:!0}catch(p){return!1}}())return a;$jscomp.initSymbol();
$jscomp.initSymbolIterator();var f=new WeakMap,e=function(c){this.data_={};this.head_=g();this.size=0;if(c){c=$jscomp.makeIterator(c);for(var b;!(b=c.next()).done;)b=b.value,this.set(b[0],b[1])}};e.prototype.set=function(c,b){var a=d(this,c);a.list||(a.list=this.data_[a.id]=[]);a.entry?a.entry.value=b:(a.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:c,value:b},a.list.push(a.entry),this.head_.previous.next=a.entry,this.head_.previous=a.entry,this.size++);return this};e.prototype.delete=
function(c){c=d(this,c);return c.entry&&c.list?(c.list.splice(c.index,1),c.list.length||delete this.data_[c.id],c.entry.previous.next=c.entry.next,c.entry.next.previous=c.entry.previous,c.entry.head=null,this.size--,!0):!1};e.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=g();this.size=0};e.prototype.has=function(c){return!!d(this,c).entry};e.prototype.get=function(c){return(c=d(this,c).entry)&&c.value};e.prototype.entries=function(){return h(this,function(c){return[c.key,
c.value]})};e.prototype.keys=function(){return h(this,function(c){return c.key})};e.prototype.values=function(){return h(this,function(c){return c.value})};e.prototype.forEach=function(c,b){for(var a=this.entries(),d;!(d=a.next()).done;)d=d.value,c.call(b,d[1],d[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var d=function(c,a){var d;d=a&&typeof a;"object"==d||"function"==d?f.has(a)?d=f.get(a):(d=""+ ++b,f.set(a,d)):d="p_"+a;var g=c.data_[d];if(g&&$jscomp.owns(c.data_,d))for(c=0;c<g.length;c++){var e=
g[c];if(a!==a&&e.key!==e.key||a===e.key)return{id:d,list:g,index:c,entry:e}}return{id:d,list:g,index:-1,entry:void 0}},h=function(c,b){var a=c.head_;return $jscomp.iteratorPrototype(function(){if(a){for(;a.head!=c.head_;)a=a.previous;for(;a.next!=a.head;)return a=a.next,{done:!1,value:b(a)};a=null}return{done:!0,value:void 0}})},g=function(){var c={};return c.previous=c.next=c.head=c},b=0;return e},"es6-impl","es3");
$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6-impl","es3");$jscomp.checkStringArgs=function(a,f,e){if(null==a)throw new TypeError("The 'this' value for String.prototype."+e+" must not be null or undefined");if(f instanceof RegExp)throw new TypeError("First argument to String.prototype."+e+" must not be a regular expression");return a+""};
$jscomp.polyfill("String.prototype.repeat",function(a){return a?a:function(a){var e=$jscomp.checkStringArgs(this,null,"repeat");if(0>a||1342177279<a)throw new RangeError("Invalid count value");a|=0;for(var d="";a;)if(a&1&&(d+=e),a>>>=1)e+=e;return d}},"es6-impl","es3");$jscomp.EXPOSE_ASYNC_EXECUTOR=!0;$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function f(){this.batch_=null}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;f.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};f.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var e=$jscomp.global.setTimeout;f.prototype.asyncExecuteFunction=function(a){e(a,0)};f.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];delete a[b];try{c()}catch(n){this.asyncThrow_(n)}}}this.batch_=null};f.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var d=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(c){b.reject(c)}};d.prototype.createResolveAndReject_=function(){function a(a){return function(d){c||(c=!0,a.call(b,d))}}var b=this,c=
!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};d.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof d)this.settleSameAsPromise_(a);else{var b;a:switch(typeof a){case "object":b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};d.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(c){this.reject_(c);return}"function"==
typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};d.prototype.reject_=function(a){this.settle_(2,a)};d.prototype.fulfill_=function(a){this.settle_(1,a)};d.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};d.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=this.onSettledCallbacks_,b=0;b<a.length;++b)a[b].call(),
a[b]=null;this.onSettledCallbacks_=null}};var h=new f;d.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};d.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(n){c.reject(n)}};d.prototype.then=function(a,b){function c(a,c){return"function"==typeof a?function(c){try{e(a(c))}catch(q){g(q)}}:c}var e,g,k=new d(function(a,c){e=a;g=c});this.callWhenSettled_(c(a,e),
c(b,g));return k};d.prototype.catch=function(a){return this.then(void 0,a)};d.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?h.asyncExecute(c):this.onSettledCallbacks_.push(function(){h.asyncExecute(c)})};d.resolve=function(a){return a instanceof d?a:new d(function(b,c){b(a)})};d.reject=function(a){return new d(function(b,c){c(a)})};
d.race=function(a){return new d(function(b,c){for(var e=$jscomp.makeIterator(a),l=e.next();!l.done;l=e.next())d.resolve(l.value).callWhenSettled_(b,c)})};d.all=function(a){var b=$jscomp.makeIterator(a),c=b.next();return c.done?d.resolve([]):new d(function(a,e){function k(c){return function(b){p[c]=b;l--;0==l&&a(p)}}var p=[],l=0;do p.push(void 0),l++,d.resolve(c.value).callWhenSettled_(k(p.length-1),e),c=b.next();while(!c.done)})};$jscomp.EXPOSE_ASYNC_EXECUTOR&&(d.$jscomp$new$AsyncExecutor=function(){return new f});
return d},"es6-impl","es3");
(function(a){function f(d){if(e[d])return e[d].exports;var h=e[d]={exports:{},id:d,loaded:!1};a[d].call(h.exports,h,h.exports,f);h.loaded=!0;return h.exports}var e={};f.m=a;f.c=e;f.p="";return f(0)})({0:function(a,f,e){a=(a=e(153))&&a.__esModule?a:{default:a};a.default.precache("/ /soundcloud-16.png /soundcloud-32.png /soundcloud-64.png /soundcloud-128.png /soundcloud-256.png /soundcloud-512.png".split(" "));a.default.router.get("/",a.default.cacheFirst);a.default.router.get(/.*client.*/,a.default.cacheFirst);
a.default.router.get(/^.*googleapis.*$/,a.default.cacheFirst);a.default.router.get(/^.*gstatic.*$/,a.default.cacheFirst);a.default.router.get(/^.*bootstrapcdn.*$/,a.default.cacheFirst);a.default.router.get(/^.*sndcdn.*$/,a.default.cacheFirst);self.addEventListener("install",function(a){a.waitUntil(self.skipWaiting())});self.addEventListener("activate",function(a){a.waitUntil(self.clients.claim())})},153:function(a,f,e){f=e(154);var d=e(155),h=e(159),g=e(161);e=e(167);h.debug("Service Worker Toolbox is loading");
self.addEventListener("install",e.installListener);self.addEventListener("activate",e.activateListener);self.addEventListener("fetch",e.fetchListener);a.exports={networkOnly:g.networkOnly,networkFirst:g.networkFirst,cacheOnly:g.cacheOnly,cacheFirst:g.cacheFirst,fastest:g.fastest,router:d,options:f,cache:h.cache,uncache:h.uncache,precache:h.precache}},154:function(a,f){f=self.registration?self.registration.scope:self.scope||(new URL("./",self.location)).href;a.exports={cache:{name:"$$$toolbox-cache$$$"+
f+"$$$",maxAgeSeconds:null,maxEntries:null},debug:!1,networkTimeoutSeconds:null,preCacheItems:[],successResponses:/^0|([123]\d\d)|(40[14567])|410$/}},155:function(a,f,e){var d=e(156),h=e(159),g=function(a,b){a=a.entries();for(var c=a.next(),d=[];!c.done;)(new RegExp(c.value[0])).test(b)&&d.push(c.value[1]),c=a.next();return d},b=function(){this.routes=new Map;this.routes.set(RegExp,new Map);this.default=null};"get post put delete head any".split(" ").forEach(function(a){b.prototype[a]=function(c,
b,d){return this.add(a,c,b,d)}});b.prototype.add=function(a,b,e,k){k=k||{};var c;b instanceof RegExp?c=RegExp:(c=k.origin||self.location.origin,c=c instanceof RegExp?c.source:c.replace(/[-\/\\^$*+?.()|[\]{}]/g,"\\$&"));a=a.toLowerCase();e=new d(a,b,e,k);this.routes.has(c)||this.routes.set(c,new Map);c=this.routes.get(c);c.has(a)||c.set(a,new Map);a=c.get(a);c=e.regexp||e.fullUrlRegExp;a.has(c.source)&&h.debug('"'+b+'" resolves to same regex as existing route.');a.set(c.source,e)};b.prototype.matchMethod=
function(a,b){var c=new URL(b),d=c.pathname;return this._match(a,g(this.routes,c.origin),d)||this._match(a,[this.routes.get(RegExp)],b)};b.prototype._match=function(a,b,d){if(0===b.length)return null;for(var c=0;c<b.length;c++){var e=b[c];if(e=e&&e.get(a.toLowerCase()))if(e=g(e,d),0<e.length)return e[0].makeHandler(d)}return null};b.prototype.match=function(a){return this.matchMethod(a.method,a.url)||this.matchMethod("any",a.url)};a.exports=new b},156:function(a,f,e){var d=(new URL("./",self.location)).pathname,
h=e(157);f=function(a,b,c,e){b instanceof RegExp?this.fullUrlRegExp=b:(0!==b.indexOf("/")&&(b=d+b),this.keys=[],this.regexp=h(b,this.keys));this.method=a;this.options=e;this.handler=c};f.prototype.makeHandler=function(a){var b;if(this.regexp){var c=this.regexp.exec(a);b={};this.keys.forEach(function(a,d){b[a.name]=c[d+1]})}return function(a){return this.handler(a,b,this.options)}.bind(this)};a.exports=f},157:function(a,f,e){function d(a,b){var d=[],e=0,h=0,k="";b=b&&b.delimiter||"/";for(var f;null!=
(f=u.exec(a));){var g=f[0],p=f[1],m=f.index,k=k+a.slice(h,m),h=m+g.length;if(p)k+=p[1];else{var l=a[h],g=f[2],p=f[3],q=f[4],n=f[5],r=f[6],m=f[7];k&&(d.push(k),k="");var l=null!=g&&null!=l&&l!==g,v="+"===r||"*"===r,r="?"===r||"*"===r;f=f[2]||b;q=q||n;d.push({name:p||e++,prefix:g||"",delimiter:f,optional:r,repeat:v,partial:l,asterisk:!!m,pattern:q?q.replace(/([=!:$\/()])/g,"\\$1"):m?".*":"[^"+c(f)+"]+?"})}}h<a.length&&(k+=a.substr(h));k&&d.push(k);return d}function h(a){return encodeURI(a).replace(/[\/?#]/g,
function(a){return"%"+a.charCodeAt(0).toString(16).toUpperCase()})}function g(a){return encodeURI(a).replace(/[?#]/g,function(a){return"%"+a.charCodeAt(0).toString(16).toUpperCase()})}function b(a){for(var c=Array(a.length),b=0;b<a.length;b++)"object"===typeof a[b]&&(c[b]=new RegExp("^(?:"+a[b].pattern+")$"));return function(b,d){var e="";b=b||{};d=(d||{}).pretty?h:encodeURIComponent;for(var f=0;f<a.length;f++){var k=a[f];if("string"===typeof k)e+=k;else{var l=b[k.name],m;if(null==l)if(k.optional){k.partial&&
(e+=k.prefix);continue}else throw new TypeError('Expected "'+k.name+'" to be defined');if(p(l)){if(!k.repeat)throw new TypeError('Expected "'+k.name+'" to not repeat, but received `'+JSON.stringify(l)+"`");if(0===l.length)if(k.optional)continue;else throw new TypeError('Expected "'+k.name+'" to not be empty');for(var t=0;t<l.length;t++){m=d(l[t]);if(!c[f].test(m))throw new TypeError('Expected all "'+k.name+'" to match "'+k.pattern+'", but received `'+JSON.stringify(m)+"`");e+=(0===t?k.prefix:k.delimiter)+
m}}else{m=k.asterisk?g(l):d(l);if(!c[f].test(m))throw new TypeError('Expected "'+k.name+'" to match "'+k.pattern+'", but received "'+m+'"');e+=k.prefix+m}}}return e}}function c(a){return a.replace(/([.+*?=^!:${}()[\]|\/\\])/g,"\\$1")}function n(a,c){a.keys=c;return a}function l(a,b,d){p(b)||(d=b||d,b=[]);d=d||{};for(var e=d.strict,k=!1!==d.end,f="",h=0;h<a.length;h++){var g=a[h];if("string"===typeof g)f+=c(g);else{var l=c(g.prefix),m="(?:"+g.pattern+")";b.push(g);g.repeat&&(m+="(?:"+l+m+")*");m=g.optional?
g.partial?l+"("+m+")?":"(?:"+l+"("+m+"))?":l+"("+m+")";f+=m}}a=c(d.delimiter||"/");h=f.slice(-a.length)===a;e||(f=(h?f.slice(0,-a.length):f)+"(?:"+a+"(?=$))?");return n(new RegExp("^"+(k?f+"$":f+(e&&h?"":"(?="+a+"|$)")),d.sensitive?"":"i"),b)}function k(a,c,b){p(c)||(b=c||b,c=[]);b=b||{};if(a instanceof RegExp){if(b=a.source.match(/\((?!\?)/g))for(var e=0;e<b.length;e++)c.push({name:e,prefix:null,delimiter:null,optional:!1,repeat:!1,partial:!1,asterisk:!1,pattern:null});return n(a,c)}if(p(a)){for(var e=
[],f=0;f<a.length;f++)e.push(k(a[f],c,b).source);a=new RegExp("(?:"+e.join("|")+")",b.sensitive?"":"i");return n(a,c)}return l(d(a,b),c,b)}var p=e(158);a.exports=k;a.exports.parse=d;a.exports.compile=function(a,c){return b(d(a,c))};a.exports.tokensToFunction=b;a.exports.tokensToRegExp=l;var u=/(\\.)|([\/.])?(?:(?:\:(\w+)(?:\(((?:\\.|[^\\()])+)\))?|\(((?:\\.|[^\\()])+)\))([+*?])?|(\*))/g},158:function(a,f){a.exports=Array.isArray||function(a){return"[object Array]"==Object.prototype.toString.call(a)}},
159:function(a,f,e){function d(a,b){b=b||{};(b.debug||c.debug)&&console.log("[sw-toolbox] "+a)}function h(a){var b;a&&a.cache&&(b=a.cache.name);b=b||c.cache.name;return caches.open(b)}function g(a,b,c){var e=a.url,f=c.maxAgeSeconds,k=c.maxEntries;a=c.name;var h=Date.now();d("Updating LRU order for "+e+". Max entries is "+k+", max age is "+f);return n.getDb(a).then(function(a){return n.setTimestampForUrl(a,e,h)}).then(function(a){return n.expireEntries(a,k,f,h)}).then(function(a){d("Successfully updated IDB.");
a=a.map(function(a){return b.delete(a)});return Promise.all(a).then(function(){d("Done with cache cleanup.")})}).catch(function(a){d(a)})}function b(a){var b=Array.isArray(a);b&&a.forEach(function(a){"string"===typeof a||a instanceof Request||(b=!1)});if(!b)throw new TypeError("The precache method expects either an array of strings and/or Requests or a Promise that resolves to an array of strings and/or Requests.");return a}var c=e(154),n=e(160),l;a.exports={debug:d,fetchAndCache:function(a,b){b=
b||{};var d=b.successResponses||c.successResponses;return fetch(a.clone()).then(function(e){"GET"===a.method&&d.test(e.status)&&h(b).then(function(d){d.put(a,e).then(function(){var e=b.cache||c.cache;(e.maxEntries||e.maxAgeSeconds)&&e.name&&(e=g.bind(null,a,d,e),l=l?l.then(e):e())})});return e.clone()})},openCache:h,renameCache:function(a,b,c){d("Renaming cache: ["+a+"] to ["+b+"]",c);return caches.delete(b).then(function(){return Promise.all([caches.open(a),caches.open(b)]).then(function(b){var c=
b[0],d=b[1];return c.keys().then(function(a){return Promise.all(a.map(function(a){return c.match(a).then(function(b){return d.put(a,b)})}))}).then(function(){return caches.delete(a)})})})},cache:function(a,b){return h(b).then(function(b){return b.add(a)})},uncache:function(a,b){return h(b).then(function(b){return b.delete(a)})},precache:function(a){a instanceof Promise||b(a);c.preCacheItems=c.preCacheItems.concat(a)},validatePrecacheInput:b}},160:function(a,f){function e(a){return new Promise(function(b,
d){var c=indexedDB.open("sw-toolbox-"+a,1);c.onupgradeneeded=function(){c.result.createObjectStore("store",{keyPath:"url"}).createIndex("timestamp","timestamp",{unique:!1})};c.onsuccess=function(){b(c.result)};c.onerror=function(){d(c.error)}})}function d(a,c,d){return c?new Promise(function(b,e){var f=1E3*c,h=[],g=a.transaction("store","readwrite"),k=g.objectStore("store");k.index("timestamp").openCursor().onsuccess=function(a){if((a=a.target.result)&&d-f>a.value.timestamp){var b=a.value.url;h.push(b);
k.delete(b);a.continue()}};g.oncomplete=function(){b(h)};g.onabort=e}):Promise.resolve([])}function h(a,c){return c?new Promise(function(b,d){var e=[],f=a.transaction("store","readwrite"),h=f.objectStore("store"),g=h.index("timestamp"),l=g.count();g.count().onsuccess=function(){var a=l.result;a>c&&(g.openCursor().onsuccess=function(b){if(b=b.target.result){var d=b.value.url;e.push(d);h.delete(d);a-e.length>c&&b.continue()}})};f.oncomplete=function(){b(e)};f.onabort=d}):Promise.resolve([])}var g={};
a.exports={getDb:function(a){a in g||(g[a]=e(a));return g[a]},setTimestampForUrl:function(a,c,d){return new Promise(function(b,e){var f=a.transaction("store","readwrite");f.objectStore("store").put({url:c,timestamp:d});f.oncomplete=function(){b(a)};f.onabort=function(){e(f.error)}})},expireEntries:function(a,c,e,f){return d(a,e,f).then(function(b){return h(a,c).then(function(a){return b.concat(a)})})}}},161:function(a,f,e){a.exports={networkOnly:e(162),networkFirst:e(163),cacheOnly:e(164),cacheFirst:e(165),
fastest:e(166)}},162:function(a,f,e){var d=e(159);a.exports=function(a,e,b){d.debug("Strategy: network only ["+a.url+"]",b);return fetch(a)}},163:function(a,f,e){var d=e(154),h=e(159);a.exports=function(a,b,c){c=c||{};var e=c.successResponses||d.successResponses,f=c.networkTimeoutSeconds||d.networkTimeoutSeconds;h.debug("Strategy: network first ["+a.url+"]",c);return h.openCache(c).then(function(b){var d,g=[],k;if(f){var l=new Promise(function(c){d=setTimeout(function(){b.match(a).then(function(a){a&&
c(a)})},1E3*f)});g.push(l)}l=h.fetchAndCache(a,c).then(function(a){d&&clearTimeout(d);if(e.test(a.status))return a;h.debug("Response was an HTTP error: "+a.statusText,c);k=a;throw Error("Bad response");}).catch(function(d){h.debug("Network or response error, fallback to cache ["+a.url+"]",c);return b.match(a).then(function(a){if(a)return a;if(k)return k;throw d;})});g.push(l);return Promise.race(g)})}},164:function(a,f,e){var d=e(159);a.exports=function(a,e,b){d.debug("Strategy: cache only ["+a.url+
"]",b);return d.openCache(b).then(function(b){return b.match(a)})}},165:function(a,f,e){var d=e(159);a.exports=function(a,e,b){d.debug("Strategy: cache first ["+a.url+"]",b);return d.openCache(b).then(function(c){return c.match(a).then(function(c){return c?c:d.fetchAndCache(a,b)})})}},166:function(a,f,e){var d=e(159),h=e(164);a.exports=function(a,b,c){d.debug("Strategy: fastest ["+a.url+"]",c);return new Promise(function(e,f){var g=!1,l=[],n=function(a){l.push(a.toString());g?f(Error('Both cache and network failed: "'+
l.join('", "')+'"')):g=!0},m=function(a){a instanceof Response?e(a):n("No result returned")};d.fetchAndCache(a.clone(),c).then(m,n);h(a,b,c).then(m,n)})}},167:function(a,f,e){function d(a){return a.reduce(function(a,b){return a.concat(b)},[])}e(168);var h=e(159),g=e(155),b=e(154);a.exports={fetchListener:function(a){var b=g.match(a.request);b?a.respondWith(b(a.request)):g.default&&"GET"===a.request.method&&0===a.request.url.indexOf("http")&&a.respondWith(g.default(a.request))},activateListener:function(a){h.debug("activate event fired");
a.waitUntil(h.renameCache(b.cache.name+"$$$inactive$$$",b.cache.name))},installListener:function(a){var c=b.cache.name+"$$$inactive$$$";h.debug("install event fired");h.debug("creating cache ["+c+"]");a.waitUntil(h.openCache({cache:{name:c}}).then(function(a){return Promise.all(b.preCacheItems).then(d).then(h.validatePrecacheInput).then(function(b){h.debug("preCache list: "+(b.join(", ")||"(none)"));return a.addAll(b)})}))}}},168:function(a,f){(function(){var a=Cache.prototype.addAll,d=navigator.userAgent.match(/(Firefox|Chrome)\/(\d+\.)/);
if(d)var f=d[1],g=parseInt(d[2]);a&&(!d||"Firefox"===f&&46<=g||"Chrome"===f&&50<=g)||(Cache.prototype.addAll=function(a){function b(a){this.name="NetworkError";this.code=19;this.message=a}var d=this;b.prototype=Object.create(Error.prototype);return Promise.resolve().then(function(){if(1>arguments.length)throw new TypeError;a=a.map(function(a){return a instanceof Request?a:String(a)});return Promise.all(a.map(function(a){"string"===typeof a&&(a=new Request(a));var c=(new URL(a.url)).protocol;if("http:"!==
c&&"https:"!==c)throw new b("Invalid scheme");return fetch(a.clone())}))}).then(function(c){if(c.some(function(a){return!a.ok}))throw new b("Incorrect response status");return Promise.all(c.map(function(b,c){return d.put(a[c],b)}))}).then(function(){})},Cache.prototype.add=function(a){return this.addAll([a])})})()}});
