(function(b){function f(e){if(c[e])return c[e].exports;var h=c[e]={exports:{},id:e,loaded:!1};b[e].call(h.exports,h,h.exports,f);h.loaded=!0;return h.exports}var c={};f.m=b;f.c=c;f.p="";return f(0)})({0:function(b,f,c){b=(b=c(223))&&b.__esModule?b:{default:b};c={policy:"fastest"};f={policy:"fastest"};c&&(c=c.policy,b.default.router.get("/",b.default[c]),b.default.router.get(/.*bundle.*/,b.default[c]));f&&(f=f.policy,b.default.router.get(/^.*googleapis.*$/,b.default[f]),b.default.router.get(/^.*gstatic.*$/,
b.default[f]),b.default.router.get(/^.*bootstrapcdn.*$/,b.default[f]),b.default.router.get(/^.*snd\.cdn.*$/,b.default[f]))},223:function(b,f,c){c(224);var e=c(225),h=c(226),l=c(230);f=c(232);l.debug("Service Worker Toolbox is loading");var a=function(a){return a.reduce(function(d,k){return d.concat(k)},[])},g=function(a){var d=Array.isArray(a);d&&a.forEach(function(a){"string"===typeof a||a instanceof Request||(d=!1)});if(!d)throw new TypeError("The precache method expects either an array of strings and/or Requests or a Promise that resolves to an array of strings and/or Requests.");
return a};self.addEventListener("install",function(m){var d=e.cache.name+"$$$inactive$$$";l.debug("install event fired");l.debug("creating cache ["+d+"]");m.waitUntil(l.openCache({cache:{name:d}}).then(function(d){return Promise.all(e.preCacheItems).then(a).then(g).then(function(a){l.debug("preCache list: "+(a.join(", ")||"(none)"));return d.addAll(a)})}))});self.addEventListener("activate",function(a){l.debug("activate event fired");a.waitUntil(l.renameCache(e.cache.name+"$$$inactive$$$",e.cache.name))});
self.addEventListener("fetch",function(a){var d=h.match(a.request);d?a.respondWith(d(a.request)):h.default&&"GET"===a.request.method&&a.respondWith(h.default(a.request))});b.exports={networkOnly:f.networkOnly,networkFirst:f.networkFirst,cacheOnly:f.cacheOnly,cacheFirst:f.cacheFirst,fastest:f.fastest,router:h,options:e,cache:function(a,d){return l.openCache(d).then(function(d){return d.add(a)})},uncache:function(a,d){return l.openCache(d).then(function(d){return d.delete(a)})},precache:function(a){a instanceof
Promise||g(a);e.preCacheItems=e.preCacheItems.concat(a)}}},224:function(b,f){(function(){var c=Cache.prototype.addAll,b=navigator.userAgent.match(/(Firefox|Chrome)\/(\d+\.)/);if(b)var h=b[1],l=parseInt(b[2]);c&&(!b||"Firefox"===h&&46<=l||"Chrome"===h&&50<=l)||(Cache.prototype.addAll=function(a){function g(a){this.name="NetworkError";this.code=19;this.message=a}var b=this;g.prototype=Object.create(Error.prototype);return Promise.resolve().then(function(){if(1>arguments.length)throw new TypeError;a=
a.map(function(a){return a instanceof Request?a:String(a)});return Promise.all(a.map(function(a){"string"===typeof a&&(a=new Request(a));var k=(new URL(a.url)).protocol;if("http:"!==k&&"https:"!==k)throw new g("Invalid scheme");return fetch(a.clone())}))}).then(function(d){if(d.some(function(a){return!a.ok}))throw new g("Incorrect response status");return Promise.all(d.map(function(d,g){return b.put(a[g],d)}))}).then(function(){})},Cache.prototype.add=function(a){return this.addAll([a])})})()},225:function(b,
f){var c;c=self.registration?self.registration.scope:self.scope||(new URL("./",self.location)).href;b.exports={cache:{name:"$$$toolbox-cache$$$"+c+"$$$",maxAgeSeconds:null,maxEntries:null},debug:!1,networkTimeoutSeconds:null,preCacheItems:[],successResponses:/^0|([123]\d\d)|(40[14567])|410$/}},226:function(b,f,c){var e=c(227),h=function(a,g){for(var b=a.entries(),d=b.next(),k=[];!d.done;)(new RegExp(d.value[0])).test(g)&&k.push(d.value[1]),d=b.next();return k},l=function(){this.routes=new Map;this.routes.set(RegExp,
new Map);this.default=null};"get post put delete head any".split(" ").forEach(function(a){l.prototype[a]=function(g,b,d){return this.add(a,g,b,d)}});l.prototype.add=function(a,g,b,d){d=d||{};var k;g instanceof RegExp?k=RegExp:(k=d.origin||self.location.origin,k=k instanceof RegExp?k.source:k.replace(/[-\/\\^$*+?.()|[\]{}]/g,"\\$&"));a=a.toLowerCase();g=new e(a,g,b,d);this.routes.has(k)||this.routes.set(k,new Map);k=this.routes.get(k);k.has(a)||k.set(a,new Map);k.get(a).set((g.regexp||g.fullUrlRegExp).source,
g)};l.prototype.matchMethod=function(a,g){var b=new URL(g),d=b.pathname;return this._match(a,h(this.routes,b.origin),d)||this._match(a,[this.routes.get(RegExp)],g)};l.prototype._match=function(a,b,c){if(0===b.length)return null;for(var d=0;d<b.length;d++){var k=b[d];if(k=k&&k.get(a.toLowerCase()))if(k=h(k,c),0<k.length)return k[0].makeHandler(c)}return null};l.prototype.match=function(a){return this.matchMethod(a.method,a.url)||this.matchMethod("any",a.url)};b.exports=new l},227:function(b,f,c){var e=
(new URL("./",self.location)).pathname,h=c(228);f=function(b,a,g,c){a instanceof RegExp?this.fullUrlRegExp=a:(0!==a.indexOf("/")&&(a=e+a),this.keys=[],this.regexp=h(a,this.keys));this.method=b;this.options=c;this.handler=g};f.prototype.makeHandler=function(b){var a;if(this.regexp){var g=this.regexp.exec(b);a={};this.keys.forEach(function(b,d){a[b.name]=g[d+1]})}return function(b){return this.handler(b,a,this.options)}.bind(this)};b.exports=f},228:function(b,f,c){function e(a){for(var d=[],b=0,k=0,
g="",c;null!=(c=p.exec(a));){var e=c[0],h=c[1],l=c.index,g=g+a.slice(k,l),k=l+e.length;if(h)g+=h[1];else{var f=a[k],e=c[2],h=c[3],r=c[4],m=c[5],q=c[6],l=c[7];g&&(d.push(g),g="");var f=null!=e&&null!=f&&f!==e,v="+"===q||"*"===q,q="?"===q||"*"===q;c=c[2]||"/";r=r||m||(l?".*":"[^"+c+"]+?");d.push({name:h||b++,prefix:e||"",delimiter:c,optional:q,repeat:v,partial:f,asterisk:!!l,pattern:r.replace(/([=!:$\/()])/g,"\\$1")})}}k<a.length&&(g+=a.substr(k));g&&d.push(g);return d}function h(a){return encodeURI(a).replace(/[\/?#]/g,
function(a){return"%"+a.charCodeAt(0).toString(16).toUpperCase()})}function l(a){return encodeURI(a).replace(/[?#]/g,function(a){return"%"+a.charCodeAt(0).toString(16).toUpperCase()})}function a(a){for(var d=Array(a.length),b=0;b<a.length;b++)"object"===typeof a[b]&&(d[b]=new RegExp("^(?:"+a[b].pattern+")$"));return function(b,g){for(var k="",c=b||{},e=(g||{}).pretty?h:encodeURIComponent,f=0;f<a.length;f++){var n=a[f];if("string"===typeof n)k+=n;else{var m=c[n.name],p;if(null==m)if(n.optional){n.partial&&
(k+=n.prefix);continue}else throw new TypeError('Expected "'+n.name+'" to be defined');if(r(m)){if(!n.repeat)throw new TypeError('Expected "'+n.name+'" to not repeat, but received `'+JSON.stringify(m)+"`");if(0===m.length)if(n.optional)continue;else throw new TypeError('Expected "'+n.name+'" to not be empty');for(var q=0;q<m.length;q++){p=e(m[q]);if(!d[f].test(p))throw new TypeError('Expected all "'+n.name+'" to match "'+n.pattern+'", but received `'+JSON.stringify(p)+"`");k+=(0===q?n.prefix:n.delimiter)+
p}}else{p=n.asterisk?l(m):e(m);if(!d[f].test(p))throw new TypeError('Expected "'+n.name+'" to match "'+n.pattern+'", but received "'+p+'"');k+=n.prefix+p}}}return k}}function g(a){return a.replace(/([.+*?=^!:${}()[\]|\/\\])/g,"\\$1")}function m(a,d){a.keys=d;return a}function d(a,d){d=d||{};for(var b=d.strict,k=!1!==d.end,c="",e=a[a.length-1],e="string"===typeof e&&/\/$/.test(e),f=0;f<a.length;f++){var h=a[f];if("string"===typeof h)c+=g(h);else{var l=g(h.prefix),m="(?:"+h.pattern+")";h.repeat&&(m+=
"(?:"+l+m+")*");m=h.optional?h.partial?l+"("+m+")?":"(?:"+l+"("+m+"))?":l+"("+m+")";c+=m}}b||(c=(e?c.slice(0,-2):c)+"(?:\\/(?=$))?");return new RegExp("^"+(k?c+"$":c+(b&&e?"":"(?=\\/|$)")),d.sensitive?"":"i")}function k(a,b,c){b=b||[];r(b)?c||(c={}):(c=b,b=[]);if(a instanceof RegExp){if(c=a.source.match(/\((?!\?)/g))for(var g=0;g<c.length;g++)b.push({name:g,prefix:null,delimiter:null,optional:!1,repeat:!1,partial:!1,asterisk:!1,pattern:null});return m(a,b)}if(r(a)){for(var g=[],h=0;h<a.length;h++)g.push(k(a[h],
b,c).source);a=new RegExp("(?:"+g.join("|")+")",c.sensitive?"":"i");return m(a,b)}a=e(a);c=d(a,c);for(g=0;g<a.length;g++)"string"!==typeof a[g]&&b.push(a[g]);return m(c,b)}var r=c(229);b.exports=k;b.exports.parse=e;b.exports.compile=function(b){return a(e(b))};b.exports.tokensToFunction=a;b.exports.tokensToRegExp=d;var p=/(\\.)|([\/.])?(?:(?:\:(\w+)(?:\(((?:\\.|[^\\()])+)\))?|\(((?:\\.|[^\\()])+)\))([+*?])?|(\*))/g},229:function(b,f){b.exports=Array.isArray||function(b){return"[object Array]"==Object.prototype.toString.call(b)}},
230:function(b,f,c){function e(b,c){c=c||{};(c.debug||a.debug)&&console.log("[sw-toolbox] "+b)}function h(b){var c;b&&b.cache&&(c=b.cache.name);c=c||a.cache.name;return caches.open(c)}function l(a,b,c){var h=a.url,f=c.maxAgeSeconds,l=c.maxEntries;a=c.name;var m=Date.now();e("Updating LRU order for "+h+". Max entries is "+l+", max age is "+f);return g.getDb(a).then(function(a){return g.setTimestampForUrl(a,h,m)}).then(function(a){return g.expireEntries(a,l,f,m)}).then(function(a){e("Successfully updated IDB.");
a=a.map(function(a){return b.delete(a)});return Promise.all(a).then(function(){e("Done with cache cleanup.")})}).catch(function(a){e(a)})}var a=c(225),g=c(231),m;b.exports={debug:e,fetchAndCache:function(b,c){c=c||{};var g=c.successResponses||a.successResponses;return fetch(b.clone()).then(function(e){"GET"===b.method&&g.test(e.status)&&h(c).then(function(g){g.put(b,e).then(function(){var e=c.cache||a.cache;(e.maxEntries||e.maxAgeSeconds)&&e.name&&(e=l.bind(null,b,g,e),m=m?m.then(e):e())})});return e.clone()})},
openCache:h,renameCache:function(a,b,c){e("Renaming cache: ["+a+"] to ["+b+"]",c);return caches.delete(b).then(function(){return Promise.all([caches.open(a),caches.open(b)]).then(function(b){var c=b[0],g=b[1];return c.keys().then(function(a){return Promise.all(a.map(function(a){return c.match(a).then(function(b){return g.put(a,b)})}))}).then(function(){return caches.delete(a)})})})}}},231:function(b,f){function c(a){return new Promise(function(b,c){var d=indexedDB.open("sw-toolbox-"+a,1);d.onupgradeneeded=
function(){d.result.createObjectStore("store",{keyPath:"url"}).createIndex("timestamp","timestamp",{unique:!1})};d.onsuccess=function(){b(d.result)};d.onerror=function(){c(d.error)}})}function e(a,b,c){return b?new Promise(function(d,e){var h=1E3*b,f=[],l=a.transaction("store","readwrite"),t=l.objectStore("store");t.index("timestamp").openCursor().onsuccess=function(a){if((a=a.target.result)&&c-h>a.value.timestamp){var b=a.value.url;f.push(b);t.delete(b);a.continue()}};l.oncomplete=function(){d(f)};
l.onabort=e}):Promise.resolve([])}function h(a,b){return b?new Promise(function(c,d){var e=[],h=a.transaction("store","readwrite"),f=h.objectStore("store"),l=f.index("timestamp"),t=l.count();l.count().onsuccess=function(){var a=t.result;a>b&&(l.openCursor().onsuccess=function(c){if(c=c.target.result){var d=c.value.url;e.push(d);f.delete(d);a-e.length>b&&c.continue()}})};h.oncomplete=function(){c(e)};h.onabort=d}):Promise.resolve([])}var l={};b.exports={getDb:function(a){a in l||(l[a]=c(a));return l[a]},
setTimestampForUrl:function(a,b,c){return new Promise(function(d,e){var h=a.transaction("store","readwrite");h.objectStore("store").put({url:b,timestamp:c});h.oncomplete=function(){d(a)};h.onabort=function(){e(h.error)}})},expireEntries:function(a,b,c,d){return e(a,c,d).then(function(c){return h(a,b).then(function(a){return c.concat(a)})})}}},232:function(b,f,c){b.exports={networkOnly:c(233),networkFirst:c(234),cacheOnly:c(235),cacheFirst:c(236),fastest:c(237)}},233:function(b,f,c){var e=c(230);b.exports=
function(b,c,a){e.debug("Strategy: network only ["+b.url+"]",a);return fetch(b)}},234:function(b,f,c){var e=c(225),h=c(230);b.exports=function(b,a,c){c=c||{};var f=c.successResponses||e.successResponses,d=c.networkTimeoutSeconds||e.networkTimeoutSeconds;h.debug("Strategy: network first ["+b.url+"]",c);return h.openCache(c).then(function(a){var e,p=[],u;if(d){var t=new Promise(function(c){e=setTimeout(function(){a.match(b).then(function(a){a&&c(a)})},1E3*d)});p.push(t)}t=h.fetchAndCache(b,c).then(function(a){e&&
clearTimeout(e);if(f.test(a.status))return a;h.debug("Response was an HTTP error: "+a.statusText,c);u=a;throw Error("Bad response");}).catch(function(d){h.debug("Network or response error, fallback to cache ["+b.url+"]",c);return a.match(b).then(function(a){if(a)return a;if(u)return u;throw d;})});p.push(t);return Promise.race(p)})}},235:function(b,f,c){var e=c(230);b.exports=function(b,c,a){e.debug("Strategy: cache only ["+b.url+"]",a);return e.openCache(a).then(function(a){return a.match(b)})}},
236:function(b,f,c){var e=c(230);b.exports=function(b,c,a){e.debug("Strategy: cache first ["+b.url+"]",a);return e.openCache(a).then(function(c){return c.match(b).then(function(c){return c?c:e.fetchAndCache(b,a)})})}},237:function(b,f,c){var e=c(230),h=c(235);b.exports=function(b,a,c){e.debug("Strategy: fastest ["+b.url+"]",c);return new Promise(function(f,d){var k=!1,r=[],p=function(a){r.push(a.toString());k?d(Error('Both cache and network failed: "'+r.join('", "')+'"')):k=!0},u=function(a){a instanceof
Response?f(a):p("No result returned")};e.fetchAndCache(b.clone(),c).then(u,p);h(b,a,c).then(u,p)})}}});
