(function(b){function g(d){if(c[d])return c[d].exports;var h=c[d]={exports:{},id:d,loaded:!1};b[d].call(h.exports,h,h.exports,g);h.loaded=!0;return h.exports}var c={};g.m=b;g.c=c;g.p="";return g(0)})({0:function(b,g,c){b=(b=c(114))&&b.__esModule?b:{default:b};b.default.router.get("/",b.default.fastest);b.default.router.get(/.*client.*/,b.default.fastest);b.default.router.get(/^.*googleapis.*$/,b.default.fastest);b.default.router.get(/^.*gstatic.*$/,b.default.fastest);b.default.router.get(/^.*bootstrapcdn.*$/,
b.default.fastest);b.default.router.get(/^.*snd\.cdn.*$/,b.default.fastest)},114:function(b,g,c){c(115);var d=c(116),h=c(117),l=c(121);g=c(123);l.debug("Service Worker Toolbox is loading");var a=function(a){return a.reduce(function(e,k){return e.concat(k)},[])},f=function(a){var e=Array.isArray(a);e&&a.forEach(function(a){"string"===typeof a||a instanceof Request||(e=!1)});if(!e)throw new TypeError("The precache method expects either an array of strings and/or Requests or a Promise that resolves to an array of strings and/or Requests.");
return a};self.addEventListener("install",function(m){var e=d.cache.name+"$$$inactive$$$";l.debug("install event fired");l.debug("creating cache ["+e+"]");m.waitUntil(l.openCache({cache:{name:e}}).then(function(e){return Promise.all(d.preCacheItems).then(a).then(f).then(function(a){l.debug("preCache list: "+(a.join(", ")||"(none)"));return e.addAll(a)})}))});self.addEventListener("activate",function(a){l.debug("activate event fired");a.waitUntil(l.renameCache(d.cache.name+"$$$inactive$$$",d.cache.name))});
self.addEventListener("fetch",function(a){var e=h.match(a.request);e?a.respondWith(e(a.request)):h.default&&"GET"===a.request.method&&a.respondWith(h.default(a.request))});b.exports={networkOnly:g.networkOnly,networkFirst:g.networkFirst,cacheOnly:g.cacheOnly,cacheFirst:g.cacheFirst,fastest:g.fastest,router:h,options:d,cache:function(a,e){return l.openCache(e).then(function(e){return e.add(a)})},uncache:function(a,e){return l.openCache(e).then(function(e){return e.delete(a)})},precache:function(a){a instanceof
Promise||f(a);d.preCacheItems=d.preCacheItems.concat(a)}}},115:function(b,g){(function(){var b=Cache.prototype.addAll,d=navigator.userAgent.match(/(Firefox|Chrome)\/(\d+\.)/);if(d)var h=d[1],l=parseInt(d[2]);b&&(!d||"Firefox"===h&&46<=l||"Chrome"===h&&50<=l)||(Cache.prototype.addAll=function(a){function f(a){this.name="NetworkError";this.code=19;this.message=a}var b=this;f.prototype=Object.create(Error.prototype);return Promise.resolve().then(function(){if(1>arguments.length)throw new TypeError;a=
a.map(function(a){return a instanceof Request?a:String(a)});return Promise.all(a.map(function(a){"string"===typeof a&&(a=new Request(a));var k=(new URL(a.url)).protocol;if("http:"!==k&&"https:"!==k)throw new f("Invalid scheme");return fetch(a.clone())}))}).then(function(e){if(e.some(function(a){return!a.ok}))throw new f("Incorrect response status");return Promise.all(e.map(function(e,f){return b.put(a[f],e)}))}).then(function(){})},Cache.prototype.add=function(a){return this.addAll([a])})})()},116:function(b,
g){var c;c=self.registration?self.registration.scope:self.scope||(new URL("./",self.location)).href;b.exports={cache:{name:"$$$toolbox-cache$$$"+c+"$$$",maxAgeSeconds:null,maxEntries:null},debug:!1,networkTimeoutSeconds:null,preCacheItems:[],successResponses:/^0|([123]\d\d)|(40[14567])|410$/}},117:function(b,g,c){var d=c(118),h=function(a,f){for(var b=a.entries(),e=b.next(),k=[];!e.done;)(new RegExp(e.value[0])).test(f)&&k.push(e.value[1]),e=b.next();return k},l=function(){this.routes=new Map;this.routes.set(RegExp,
new Map);this.default=null};"get post put delete head any".split(" ").forEach(function(a){l.prototype[a]=function(f,b,e){return this.add(a,f,b,e)}});l.prototype.add=function(a,f,b,e){e=e||{};var k;f instanceof RegExp?k=RegExp:(k=e.origin||self.location.origin,k=k instanceof RegExp?k.source:k.replace(/[-\/\\^$*+?.()|[\]{}]/g,"\\$&"));a=a.toLowerCase();f=new d(a,f,b,e);this.routes.has(k)||this.routes.set(k,new Map);k=this.routes.get(k);k.has(a)||k.set(a,new Map);k.get(a).set((f.regexp||f.fullUrlRegExp).source,
f)};l.prototype.matchMethod=function(a,f){var b=new URL(f),e=b.pathname;return this._match(a,h(this.routes,b.origin),e)||this._match(a,[this.routes.get(RegExp)],f)};l.prototype._match=function(a,f,b){if(0===f.length)return null;for(var e=0;e<f.length;e++){var k=f[e];if(k=k&&k.get(a.toLowerCase()))if(k=h(k,b),0<k.length)return k[0].makeHandler(b)}return null};l.prototype.match=function(a){return this.matchMethod(a.method,a.url)||this.matchMethod("any",a.url)};b.exports=new l},118:function(b,g,c){var d=
(new URL("./",self.location)).pathname,h=c(119);g=function(b,a,f,c){a instanceof RegExp?this.fullUrlRegExp=a:(0!==a.indexOf("/")&&(a=d+a),this.keys=[],this.regexp=h(a,this.keys));this.method=b;this.options=c;this.handler=f};g.prototype.makeHandler=function(b){var a;if(this.regexp){var f=this.regexp.exec(b);a={};this.keys.forEach(function(b,e){a[b.name]=f[e+1]})}return function(b){return this.handler(b,a,this.options)}.bind(this)};b.exports=g},119:function(b,g,c){function d(a){for(var e=[],b=0,k=0,
f="",d;null!=(d=n.exec(a));){var c=d[0],h=d[1],l=d.index,f=f+a.slice(k,l),k=l+c.length;if(h)f+=h[1];else{var u=a[k],c=d[2],h=d[3],p=d[4],g=d[5],m=d[6],l=d[7];f&&(e.push(f),f="");var u=null!=c&&null!=u&&u!==c,w="+"===m||"*"===m,m="?"===m||"*"===m;d=d[2]||"/";p=p||g||(l?".*":"[^"+d+"]+?");e.push({name:h||b++,prefix:c||"",delimiter:d,optional:m,repeat:w,partial:u,asterisk:!!l,pattern:p.replace(/([=!:$\/()])/g,"\\$1")})}}k<a.length&&(f+=a.substr(k));f&&e.push(f);return e}function h(a){return encodeURI(a).replace(/[\/?#]/g,
function(a){return"%"+a.charCodeAt(0).toString(16).toUpperCase()})}function l(a){return encodeURI(a).replace(/[?#]/g,function(a){return"%"+a.charCodeAt(0).toString(16).toUpperCase()})}function a(a){for(var e=Array(a.length),b=0;b<a.length;b++)"object"===typeof a[b]&&(e[b]=new RegExp("^(?:"+a[b].pattern+")$"));return function(b,f){for(var k="",d=b||{},c=(f||{}).pretty?h:encodeURIComponent,t=0;t<a.length;t++){var m=a[t];if("string"===typeof m)k+=m;else{var g=d[m.name],n;if(null==g)if(m.optional){m.partial&&
(k+=m.prefix);continue}else throw new TypeError('Expected "'+m.name+'" to be defined');if(p(g)){if(!m.repeat)throw new TypeError('Expected "'+m.name+'" to not repeat, but received `'+JSON.stringify(g)+"`");if(0===g.length)if(m.optional)continue;else throw new TypeError('Expected "'+m.name+'" to not be empty');for(var v=0;v<g.length;v++){n=c(g[v]);if(!e[t].test(n))throw new TypeError('Expected all "'+m.name+'" to match "'+m.pattern+'", but received `'+JSON.stringify(n)+"`");k+=(0===v?m.prefix:m.delimiter)+
n}}else{n=m.asterisk?l(g):c(g);if(!e[t].test(n))throw new TypeError('Expected "'+m.name+'" to match "'+m.pattern+'", but received "'+n+'"');k+=m.prefix+n}}}return k}}function f(a){return a.replace(/([.+*?=^!:${}()[\]|\/\\])/g,"\\$1")}function m(a,e){a.keys=e;return a}function e(a,e){e=e||{};for(var b=e.strict,k=!1!==e.end,d="",c=a[a.length-1],c="string"===typeof c&&/\/$/.test(c),m=0;m<a.length;m++){var h=a[m];if("string"===typeof h)d+=f(h);else{var l=f(h.prefix),g="(?:"+h.pattern+")";h.repeat&&(g+=
"(?:"+l+g+")*");g=h.optional?h.partial?l+"("+g+")?":"(?:"+l+"("+g+"))?":l+"("+g+")";d+=g}}b||(d=(c?d.slice(0,-2):d)+"(?:\\/(?=$))?");return new RegExp("^"+(k?d+"$":d+(b&&c?"":"(?=\\/|$)")),e.sensitive?"":"i")}function k(a,b,f){b=b||[];p(b)?f||(f={}):(f=b,b=[]);if(a instanceof RegExp){if(f=a.source.match(/\((?!\?)/g))for(var c=0;c<f.length;c++)b.push({name:c,prefix:null,delimiter:null,optional:!1,repeat:!1,partial:!1,asterisk:!1,pattern:null});return m(a,b)}if(p(a)){for(var c=[],h=0;h<a.length;h++)c.push(k(a[h],
b,f).source);a=new RegExp("(?:"+c.join("|")+")",f.sensitive?"":"i");return m(a,b)}a=d(a);f=e(a,f);for(c=0;c<a.length;c++)"string"!==typeof a[c]&&b.push(a[c]);return m(f,b)}var p=c(120);b.exports=k;b.exports.parse=d;b.exports.compile=function(e){return a(d(e))};b.exports.tokensToFunction=a;b.exports.tokensToRegExp=e;var n=/(\\.)|([\/.])?(?:(?:\:(\w+)(?:\(((?:\\.|[^\\()])+)\))?|\(((?:\\.|[^\\()])+)\))([+*?])?|(\*))/g},120:function(b,g){b.exports=Array.isArray||function(b){return"[object Array]"==Object.prototype.toString.call(b)}},
121:function(b,g,c){function d(e,b){b=b||{};(b.debug||a.debug)&&console.log("[sw-toolbox] "+e)}function h(b){var f;b&&b.cache&&(f=b.cache.name);f=f||a.cache.name;return caches.open(f)}function l(a,b,c){var h=a.url,m=c.maxAgeSeconds,l=c.maxEntries;a=c.name;var g=Date.now();d("Updating LRU order for "+h+". Max entries is "+l+", max age is "+m);return f.getDb(a).then(function(a){return f.setTimestampForUrl(a,h,g)}).then(function(a){return f.expireEntries(a,l,m,g)}).then(function(a){d("Successfully updated IDB.");
a=a.map(function(a){return b.delete(a)});return Promise.all(a).then(function(){d("Done with cache cleanup.")})}).catch(function(a){d(a)})}var a=c(116),f=c(122),m;b.exports={debug:d,fetchAndCache:function(b,f){f=f||{};var d=f.successResponses||a.successResponses;return fetch(b.clone()).then(function(c){"GET"===b.method&&d.test(c.status)&&h(f).then(function(d){d.put(b,c).then(function(){var c=f.cache||a.cache;(c.maxEntries||c.maxAgeSeconds)&&c.name&&(c=l.bind(null,b,d,c),m=m?m.then(c):c())})});return c.clone()})},
openCache:h,renameCache:function(a,b,f){d("Renaming cache: ["+a+"] to ["+b+"]",f);return caches.delete(b).then(function(){return Promise.all([caches.open(a),caches.open(b)]).then(function(b){var f=b[0],c=b[1];return f.keys().then(function(a){return Promise.all(a.map(function(a){return f.match(a).then(function(b){return c.put(a,b)})}))}).then(function(){return caches.delete(a)})})})}}},122:function(b,g){function c(a){return new Promise(function(b,c){var e=indexedDB.open("sw-toolbox-"+a,1);e.onupgradeneeded=
function(){e.result.createObjectStore("store",{keyPath:"url"}).createIndex("timestamp","timestamp",{unique:!1})};e.onsuccess=function(){b(e.result)};e.onerror=function(){c(e.error)}})}function d(a,b,c){return b?new Promise(function(e,d){var h=1E3*b,l=[],g=a.transaction("store","readwrite"),q=g.objectStore("store");q.index("timestamp").openCursor().onsuccess=function(a){if((a=a.target.result)&&c-h>a.value.timestamp){var b=a.value.url;l.push(b);q.delete(b);a.continue()}};g.oncomplete=function(){e(l)};
g.onabort=d}):Promise.resolve([])}function h(a,b){return b?new Promise(function(c,e){var d=[],h=a.transaction("store","readwrite"),g=h.objectStore("store"),l=g.index("timestamp"),q=l.count();l.count().onsuccess=function(){var a=q.result;a>b&&(l.openCursor().onsuccess=function(c){if(c=c.target.result){var e=c.value.url;d.push(e);g.delete(e);a-d.length>b&&c.continue()}})};h.oncomplete=function(){c(d)};h.onabort=e}):Promise.resolve([])}var l={};b.exports={getDb:function(a){a in l||(l[a]=c(a));return l[a]},
setTimestampForUrl:function(a,b,c){return new Promise(function(e,d){var h=a.transaction("store","readwrite");h.objectStore("store").put({url:b,timestamp:c});h.oncomplete=function(){e(a)};h.onabort=function(){d(h.error)}})},expireEntries:function(a,b,c,e){return d(a,c,e).then(function(c){return h(a,b).then(function(a){return c.concat(a)})})}}},123:function(b,g,c){b.exports={networkOnly:c(124),networkFirst:c(125),cacheOnly:c(126),cacheFirst:c(127),fastest:c(128)}},124:function(b,g,c){var d=c(121);b.exports=
function(b,c,a){d.debug("Strategy: network only ["+b.url+"]",a);return fetch(b)}},125:function(b,g,c){var d=c(116),h=c(121);b.exports=function(b,a,c){c=c||{};var g=c.successResponses||d.successResponses,e=c.networkTimeoutSeconds||d.networkTimeoutSeconds;h.debug("Strategy: network first ["+b.url+"]",c);return h.openCache(c).then(function(a){var d,n=[],r;if(e){var q=new Promise(function(c){d=setTimeout(function(){a.match(b).then(function(a){a&&c(a)})},1E3*e)});n.push(q)}q=h.fetchAndCache(b,c).then(function(a){d&&
clearTimeout(d);if(g.test(a.status))return a;h.debug("Response was an HTTP error: "+a.statusText,c);r=a;throw Error("Bad response");}).catch(function(d){h.debug("Network or response error, fallback to cache ["+b.url+"]",c);return a.match(b).then(function(a){if(a)return a;if(r)return r;throw d;})});n.push(q);return Promise.race(n)})}},126:function(b,g,c){var d=c(121);b.exports=function(b,c,a){d.debug("Strategy: cache only ["+b.url+"]",a);return d.openCache(a).then(function(a){return a.match(b)})}},
127:function(b,g,c){var d=c(121);b.exports=function(b,c,a){d.debug("Strategy: cache first ["+b.url+"]",a);return d.openCache(a).then(function(c){return c.match(b).then(function(c){return c?c:d.fetchAndCache(b,a)})})}},128:function(b,g,c){var d=c(121),h=c(126);b.exports=function(b,a,c){d.debug("Strategy: fastest ["+b.url+"]",c);return new Promise(function(g,e){var k=!1,p=[],n=function(a){p.push(a.toString());k?e(Error('Both cache and network failed: "'+p.join('", "')+'"')):k=!0},r=function(a){a instanceof
Response?g(a):n("No result returned")};d.fetchAndCache(b.clone(),c).then(r,n);h(b,a,c).then(r,n)})}}});
